Dz6 background image
js-tasks-ru/htmlcss-20230911-4_dvshapkin pull request #14
Opened 2023-10-05 06:30 UTC by dvshapkin

2023-10-05 06:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-05 20:54 UTC, GSemikozov requested changes

2023-10-05 20:54 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (max-width: 400px) {
все медиа-запросы пишем ниже класса блока (то что работает как версию по умолчанию)

2023-10-05 20:54 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (max-width: 400px) {
и поскольку здесь mobile-first - этот медиа-запрос лишний, это должно быть значение по умолчанию

2023-10-05 20:54 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (min-width: 401px) and (max-width: 768px) {
все max-width будут лишними

2023-10-06 05:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-06 05:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-06 06:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-06 06:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-07 21:24 UTC, GSemikozov approved these changes

2023-10-07 21:24 UTC, merged