Dz3 button
js-tasks-ru/htmlcss-20230911-4_dvshapkin pull request #4
Opened 2023-09-21 08:12 UTC by dvshapkin

2023-09-21 08:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-21 08:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-21 08:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-21 20:27 UTC, GSemikozov requested changes

2023-09-21 20:27 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  min-width: 189px;
не обязательно

2023-09-21 20:27 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  min-height: 48px;
просто height

2023-09-21 20:27 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  line-height: normal;
не хватает font-family

2023-09-21 20:27 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  cursor: not-allowed;
лучше pointer-events: none

2023-09-21 20:27 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  line-height: normal;
не хватает паддингов

2023-09-22 03:18 UTC, dvshapkin commented on 03-lection1/01-button/button.css
> +  line-height: normal;
font-family наследуется из main.css - Roboto

2023-09-22 13:09 UTC, GSemikozov requested changes

2023-09-22 13:09 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 0 2em;
а чему тут равны 2em? я не советую сейчас применять эти единицы измерения.

2023-09-22 13:09 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 0 2em;
достаточно указать `padding: 15px 15px 14px`

2023-09-22 15:24 UTC, dvshapkin commented on 03-lection1/01-button/button.css
> +  padding: 0 2em;
ok

2023-09-24 21:39 UTC, GSemikozov approved these changes

2023-09-24 21:39 UTC, merged