Dz4 cards on index
js-tasks-ru/htmlcss-20230911-4_dvshapkin pull request #6
Opened 2023-09-24 07:01 UTC by dvshapkin

2023-09-24 07:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-24 08:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-24 21:42 UTC, GSemikozov requested changes
надо подлить свежий апстрим мастер

2023-09-24 21:42 UTC, GSemikozov commented on components/container/container.css
> +  align-items:center;
лишнее (это же не флекс контейнер, верно?))

2023-09-25 21:19 UTC, GSemikozov requested changes

2023-09-25 21:19 UTC, GSemikozov commented on components/content/content.css
> +.content .content__button {
не надо так) и кнопка эта тоже не нужна)

2023-09-27 19:48 UTC, GSemikozov submitted a review, later dismissed

2023-09-27 19:48 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-09-27 19:51 UTC, GSemikozov requested changes

2023-09-27 19:51 UTC, GSemikozov commented on assets/css/main.css
> +@import '../..//03-lection1/01-button/button.css';
вот здесь одна `/` лишняя, из-за чего могут быть проблемы

2023-09-28 03:26 UTC, dvshapkin commented on assets/css/main.css
> +@import '../..//03-lection1/01-button/button.css';
спасибо!

2023-09-28 04:57 UTC, GSemikozov approved these changes

2023-09-28 04:57 UTC, merged