Dz4 histogram
js-tasks-ru/htmlcss-20230911-4_dvshapkin pull request #7
Opened 2023-09-24 10:42 UTC by dvshapkin

2023-09-24 10:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-24 22:07 UTC, GSemikozov requested changes
conflicts

2023-09-24 22:07 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    border-radius: 6px;
8

2023-09-24 22:07 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin-bottom: 40px;
39

2023-09-24 22:07 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__left {
.histogram__info

2023-09-24 22:07 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__right {
лишнее, здесь сразу можно добавить .histogram__link

2023-09-24 22:07 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex-basis: 10px;
9

2023-09-24 22:07 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    min-height: 100%;
без min

2023-09-25 05:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-25 05:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-25 05:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-25 05:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-25 05:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-25 06:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-25 21:20 UTC, GSemikozov requested changes

2023-09-25 21:20 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  text-decoration: none;
margin-top: 3px?

2023-09-25 21:20 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +      <a class="histogram__link histogram__text histogram__text_small" href="#">View all</a>
это все-таки отдельный элемент, вместо такого микса классов я бы рекомендовал описать все необходимые стили в классе элемента

2023-09-27 19:48 UTC, GSemikozov approved these changes

2023-09-27 19:48 UTC, merged